---
name: Merge ot master

on:
  push:
    branches:
      - master

jobs:
  terraform_plan:
    uses: spacedog/github-workflows/.github/workflows/terraform-plan.yml@main
    with:
      post_comment: false
      environment: development
      terraform_version: latest