name: "Terraform Apply"

on:
  push:
    branches:
      - master
      - main

jobs:
  apply_dev:
    runs-on: ubuntu-latest
    name: "Apply for Dev"
    environment: development
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          label: development
          workspace: dev
  apply_prod:
    runs-on: ubuntu-latest
    name: "Apply for Prod"
    need: apply_dev
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          label: production
          workspace: prod
