name: "Terraform apply on Release"
on:
  push:
    tags:
      - v1.**

jobs:
  apply_prod:
    runs-on: ubuntu-latest
    name: "Apply for Prod"
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          label: production
          workspace: prod
