name: "Terraform Plan"

on:
  - pull_request

jobs:
  plan_dev:
    runs-on: ubuntu-latest
    name:  Create Plan for Dev
    environment: development
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          label: development
          workspace: dev
