---
name: Set github environment

on:
  push:
    branches:
      - master

env:
  extra_envs: |
    env1={\"dev\"=\"${{ secrets.env1 }}\"}
    env2=${{ secrets.env2}}

jobs:
  set_github_env:
    name: Set github environment variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo -e "${extra_envs}" >> $GITHUB_ENV
      - name: Get environment
        run: |
          env
